### ISSUE TITLE
Problem recognizing EOF

### ISSUE THREAD

**Issue by gusandrianos** [acidghost/language-lex-flex-new#1]
Hello!

First of all, thanks for the extension, it's really helpful for my compilers class :)
I have a problem.
The EOF rule should be <<EOF>>, not <EOF>.
The standard flex package from the ubuntu repos, works with the former only.
Can you fix it so it doesn't show up red?

Thank you.
The error with <EOF>
[screenshot from 2018-01-17 17-20-02](https://user-images.githubusercontent.com/17255848/35050104-b15da0c0-fbaa-11e7-986a-da6415644794.png)
Current view in Atom with valid Flex syntax.
[screenshot from 2018-01-17 17-18-39](https://user-images.githubusercontent.com/17255848/35050039-84de41a8-fbaa-11e7-831e-693037d05086.png)

**Comment by acidghost** [comment]
If you could give a go to the pull request I'll be happy to merge it 😊

**Comment by gusandrianos** [comment]
I'll give it a go when I find the time :)
